

CREATE TABLE QRTZ_FIRED_TRIGGERS1 (
  SCHED_NAME1 VARCHAR(120) NOT NULL,
  ENTRY_ID1 VARCHAR (95) NOT NULL,
  TRIGGER_NAME1 VARCHAR (200) NOT NULL,
  TRIGGER_GROUP1 VARCHAR (200) NOT NULL,
  INSTANCE_NAME1 VARCHAR (200) NOT NULL,
  FIRED_TIME1 BIGINT NOT NULL,
  SCHED_TIME1 BIGINT NOT NULL,
  PRIORITY INTEGER NOT NULL,
  STATE VARCHAR (16) NOT NULL,
  JOB_NAME1 VARCHAR (200),
  JOB_GROUP1 VARCHAR (200),
  IS_NONCONCURRENT BOOLEAN,
  REQUESTS_RECOVERY BOOLEAN
);

CREATE TABLE QRTZ_PAUSED_TRIGGER_GRPS1 (
  SCHED_NAME1 VARCHAR(120) NOT NULL,
  TRIGGER_GROUP1 VARCHAR (200) NOT NULL
);

CREATE TABLE QRTZ_SCHEDULER_STATE1 (
  SCHED_NAME1 VARCHAR(120) NOT NULL,
  INSTANCE_NAME1 VARCHAR (200) NOT NULL,
  LAST_CHECKIN_TIME1 BIGINT NOT NULL,
  CHECKIN_INTERVAL1 BIGINT NOT NULL
);

CREATE TABLE QRTZ_LOCKS1 (
  SCHED_NAME1 VARCHAR(120) NOT NULL,
  LOCK_NAME1 VARCHAR (40) NOT NULL
);

CREATE TABLE QRTZ_JOB_DETAILS1 (
  SCHED_NAME1 VARCHAR(120) NOT NULL,
  JOB_NAME1 VARCHAR (200) NOT NULL,
  JOB_GROUP1 VARCHAR (200) NOT NULL,
  DESCRIPTION VARCHAR (250),
  JOB_CLASS_NAME1 VARCHAR (250) NOT NULL,
  IS_DURABLE BOOLEAN NOT NULL,
  IS_NONCONCURRENT BOOLEAN NOT NULL,
  IS_UPDATE_DATA BOOLEAN NOT NULL,
  REQUESTS_RECOVERY BOOLEAN NOT NULL,
  JOB_DATA1 BLOB
);

CREATE TABLE QRTZ_SIMPLE_TRIGGERS1 (
  SCHED_NAME1 VARCHAR(120) NOT NULL,
  TRIGGER_NAME1 VARCHAR (200) NOT NULL,
  TRIGGER_GROUP1 VARCHAR (200) NOT NULL,
  REPEAT_COUNT1 BIGINT NOT NULL,
  REPEAT_INTERVAL1 BIGINT NOT NULL,
  TIMES_TRIGGERED1 BIGINT NOT NULL
);

CREATE TABLE QRTZ_SIMPROP_TRIGGERS1
  (
    SCHED_NAME1 VARCHAR(120) NOT NULL,
    TRIGGER_NAME1 VARCHAR(200) NOT NULL,
    TRIGGER_GROUP1 VARCHAR(200) NOT NULL,
    STR_PROP_11 VARCHAR(512),
    STR_PROP_21 VARCHAR(512),
    STR_PROP_31 VARCHAR(512),
    INT_PROP_11 INTEGER,
    INT_PROP_21 INTEGER,
    LONG_PROP_11 BIGINT,
    LONG_PROP_21 BIGINT,
    DEC_PROP_11 NUMERIC(13,4),
    DEC_PROP_21 NUMERIC(13,4),
    BOOL_PROP_1 BOOLEAN,
    BOOL_PROP_2 BOOLEAN
);

CREATE TABLE QRTZ_BLOB_TRIGGERS1 (
  SCHED_NAME1 VARCHAR(120) NOT NULL,
  TRIGGER_NAME1 VARCHAR (200) NOT NULL,
  TRIGGER_GROUP1 VARCHAR (200) NOT NULL,
  BLOB_DATA1 BLOB
);

CREATE TABLE QRTZ_TRIGGERS1 (
  SCHED_NAME1 VARCHAR(120) NOT NULL,
  TRIGGER_NAME1 VARCHAR (200) NOT NULL,
  TRIGGER_GROUP1 VARCHAR (200) NOT NULL,
  JOB_NAME1 VARCHAR (200) NOT NULL,
  JOB_GROUP1 VARCHAR (200) NOT NULL,
  DESCRIPTION VARCHAR (250),
  NEXT_FIRE_TIME1 BIGINT,
  PREV_FIRE_TIME1 BIGINT,
  PRIORITY INTEGER,
  TRIGGER_STATE1 VARCHAR (16) NOT NULL,
  TRIGGER_TYPE1 VARCHAR (8) NOT NULL,
  START_TIME1 BIGINT NOT NULL,
  END_TIME1 BIGINT,
  CALENDAR_NAME1 VARCHAR (200),
  MISFIRE_INSTR1 SMALLINT,
  JOB_DATA1 BLOB
);

ALTER TABLE QRTZ_CALENDARS1  ADD
  CONSTRAINT PK_QRTZ_CALENDARS1 PRIMARY KEY
  (
    SCHED_NAME1,
    CALENDAR_NAME1
  );

ALTER TABLE QRTZ_CRON_TRIGGERS1  ADD
  CONSTRAINT PK_QRTZ_CRON_TRIGGERS1 PRIMARY KEY
  (
    SCHED_NAME1,
    TRIGGER_NAME1,
    TRIGGER_GROUP1
  );

ALTER TABLE QRTZ_FIRED_TRIGGERS1  ADD
  CONSTRAINT PK_QRTZ_FIRED_TRIGGERS1 PRIMARY KEY
  (
    SCHED_NAME1,
    ENTRY_ID1
  );

ALTER TABLE QRTZ_PAUSED_TRIGGER_GRPS1  ADD
  CONSTRAINT PK_QRTZ_PAUSED_TRIGGER_GRPS1 PRIMARY KEY
  (
    SCHED_NAME1,
    TRIGGER_GROUP1
  );

ALTER TABLE QRTZ_SCHEDULER_STATE1  ADD
  CONSTRAINT PK_QRTZ_SCHEDULER_STATE1 PRIMARY KEY
  (
    SCHED_NAME1,
    INSTANCE_NAME1
  );

ALTER TABLE QRTZ_LOCKS1  ADD
  CONSTRAINT PK_QRTZ_LOCKS1 PRIMARY KEY
  (
    SCHED_NAME1,
    LOCK_NAME1
  );

ALTER TABLE QRTZ_JOB_DETAILS1  ADD
  CONSTRAINT PK_QRTZ_JOB_DETAILS1 PRIMARY KEY
  (
    SCHED_NAME1,
    JOB_NAME1,
    JOB_GROUP1
  );

ALTER TABLE QRTZ_SIMPLE_TRIGGERS1  ADD
  CONSTRAINT PK_QRTZ_SIMPLE_TRIGGERS1 PRIMARY KEY
  (
    SCHED_NAME1,
    TRIGGER_NAME1,
    TRIGGER_GROUP1
  );

ALTER TABLE QRTZ_SIMPROP_TRIGGERS1  ADD
  CONSTRAINT PK_QRTZ_SIMPROP_TRIGGERS1 PRIMARY KEY
  (
    SCHED_NAME1,
    TRIGGER_NAME1,
    TRIGGER_GROUP1
  );

ALTER TABLE QRTZ_TRIGGERS1  ADD
  CONSTRAINT PK_QRTZ_TRIGGERS1 PRIMARY KEY
  (
    SCHED_NAME1,
    TRIGGER_NAME1,
    TRIGGER_GROUP1
  );

ALTER TABLE QRTZ_CRON_TRIGGERS1 ADD
  CONSTRAINT FK_QRTZ_CRON_TRIGGERS_QRTZ_TRIGGERS1 FOREIGN KEY
  (
    SCHED_NAME1,
    TRIGGER_NAME1,
    TRIGGER_GROUP1
  ) REFERENCES QRTZ_TRIGGERS1 (
    SCHED_NAME1,
    TRIGGER_NAME1,
    TRIGGER_GROUP1
  ) ON DELETE CASCADE;


ALTER TABLE QRTZ_SIMPLE_TRIGGERS1 ADD
  CONSTRAINT FK_QRTZ_SIMPLE_TRIGGERS_QRTZ_TRIGGERS1 FOREIGN KEY
  (
    SCHED_NAME1,
    TRIGGER_NAME1,
    TRIGGER_GROUP1
  ) REFERENCES QRTZ_TRIGGERS1 (
    SCHED_NAME1,
    TRIGGER_NAME1,
    TRIGGER_GROUP1
  ) ON DELETE CASCADE;

ALTER TABLE QRTZ_SIMPROP_TRIGGERS1 ADD
  CONSTRAINT FK_QRTZ_SIMPROP_TRIGGERS_QRTZ_TRIGGERS1 FOREIGN KEY
  (
    SCHED_NAME1,
    TRIGGER_NAME1,
    TRIGGER_GROUP1
  ) REFERENCES QRTZ_TRIGGERS1 (
    SCHED_NAME1,
    TRIGGER_NAME1,
    TRIGGER_GROUP1
  ) ON DELETE CASCADE;


ALTER TABLE QRTZ_TRIGGERS ADD1
  CONSTRAINT FK_QRTZ_TRIGGERS_QRTZ_JOB_DETAILS1 FOREIGN KEY
  (
    SCHED_NAME1,
    JOB_NAME1,
    JOB_GROUP1
  ) REFERENCES QRTZ_JOB_DETAILS1 (
    SCHED_NAME1,
    JOB_NAME1,
    JOB_GROUP1
  );
